model:
  base_model: 'SeqModel'
  seq_len: 8
  batch_size: 1024
  num_workers: 7
  max_epochs: 50
  trtype: 'test'
  hidden_dim: 128
  dropout: 0.05

loss:
  beta: 1.0
  loss_mult: 100

opti:
  name: 'nadam'
  lr: 0.002
  wd: 1e-5

scheduler:
  name: 'step'
  gamma: 0.2
  steps:
    - 20
    - 40
  div_factor: 10
  pct_start: 0.0
  final_div_factor: 100
